export {default as Homepage} from './homepage/Homepage.jsx'
export  {default as Login} from './login/Login.jsx'
export {default as Register} from './register/Register.jsx'
export {default as Settings} from './settings/Settings.jsx'
export {default as Single} from './single/Single.jsx'
export {default as Write } from './write/Write.jsx'
